repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: ^(pnpm-lock.yaml|Cargo.lock)$
  - repo: local
    hooks:
      - id: eslint-fix
        name: eslint fix
        entry: pnpm eslint --fix
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts))$"
      - id: prettier-write
        name: prettier write
        entry: pnpm prettier --write
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|yaml|md)$"
